version: "3.9"

services:

  backend:

    build: ./apps/api_fixed

    ports:
      - "8000:8000"

    volumes:
      - ./apps/api_fixed:/app

    env_file:
      - ./apps/api_fixed/.env

    depends_on:
      - db

  frontend:

    build: ./apps/web_fixed

    ports:
      - "3000:3000"

    volumes:
      - ./apps/web_fixed:/app
      - /app/node_modules

    depends_on:
      - backend

  db:

    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rootpilot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: